### ISSUE TITLE
发布版本 v3.1.3

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#108]
- 功能
  - 歌词制作
    - #99 修复制作歌词过程中编辑歌词时的播放和暂停不合理的问题
    - #121 (#115) 输出的时间标签格式由3位小数位调整为2位小数位 
  - 歌曲歌词下载
    - #98 ( #97 ) 解决获取到的歌词内容为空的问题
    - #103 #105 #106 (#91) 修复文件名称含有特殊字符时保存失败问题 
  - 音频处理与控制
    - #100 (#95) 修复某些歌曲播放结束时程序崩溃问题
  - 设置
    - #101 (#59 #88) 使用新的数据文件路径以解决权限问题 
  - 界面
    - #120 调整了标签‘当前版本号：’的宽度 
- 代码
  - 优化
    - #86 为子对象的初始化添加大括号以通过 GCC 5 的静态检查
    - #111 匹配文件名以适应 macOS 的某些大小写敏感的文件系统
    - #112 更正生成的应用程序的文件名的大小写
    - #113 在 Shadow build 禁用时阻止构建以避免输出文件被覆盖
  - 升级
    - #110 (#29) 限制 Qt 为 5.12.4 及更高版本以使用 OpenSSL 1.1.1

**Comment by xiebruce** [comment]
支持支持！啥时候发呢

**Comment by pzhlkj6612** [comment]
@xiebruce 你好。

Windows 平台的打包还有一些问题，得再等等。

**Comment by xiebruce** [comment]
好的，辛苦！

**Comment by BensonLaur** [comment]
+ 废弃该 issue，在新 issue #180 中继续
