### ISSUE TITLE
希望歌词时间轴能够设置2个小数点位数，以提高歌词文件的适配性

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#115]
[该建议来自 博客园用户[许云封](https://home.cnblogs.com/u/2275829/) 在 BesLyric 介绍博客的 [4 楼评论](https://www.cnblogs.com/BensonLaur/p/9695769.html#4796908)]

### 问题验证
经过验证，目前播放器 [爱奇艺万能联播](http://static-s.iqiyi.com/wnbf/get.html) 确实无法载入3 位小数点的时间轴歌词，验证过程如下：
![不见图请翻墙](https://user-images.githubusercontent.com/11558955/104082565-32fb2000-5272-11eb-959a-66de0a72883e.png)
+ 下载 爱奇艺万能联播 客户端
+ 准备包含 3 位小数 和 2 位小数时间轴的 LRC 歌词文件 和 对应歌曲文件
+ 播放歌曲
+ 可见只有 2 位小数点 的歌词被载入显示

### BesLyric 功能支持评估
1. 功能合理性？
虽然 BesLyric 是专门设计为 **为网易云音乐制作歌词** ，多支持 2 位数 确实可提高软件输出文件的适配性。

2. BesLyric 添加该功能是否会影响现有功能？
是否影响，既是，若提供 2 位小数点 设置，如果现有网易云音乐用户制作歌词时，设置为 2 位小数，其生成的 LRC 歌词是否可以被网易云音乐平台所接受？
通过从网易云音乐下载其LRC歌词，发现下载到的歌词有包含有2位小数点的情况，故可推断 网易云音乐应该是支持 2 位 和 3 位 小数点时间轴歌词的。
比如通过 BesLyric 从网易云音乐平台上，下载由 “*川鑫联组合*”创作的歌曲  [我们的歌](https://music.163.com/#/song?id=1378938506&userid=349301179) 的 LRC 歌词，可发现前2行歌词时间是 3 位小数，后面都为 2 位小数
![不见图请翻墙](https://user-images.githubusercontent.com/11558955/104082874-b9186600-5274-11eb-91ca-b42acfe9867d.png)
 
### BesLyric 功能设想/设计
1. 关于选项设计，由于小数点位数多为 3 位，且多数设计良好的软件都兼容不同小数位数，只有特定情况下（某些软件）才需要 2 位小数，故可考虑设计为 2 个 `combobox` 控件互斥二选一，类似当前设置页面的 “*命名格式*” 设置
2. 关于设置位置，可以考虑放在 “歌词制作” 分类设置下 
![不见图请翻墙](https://user-images.githubusercontent.com/11558955/104083031-0812cb00-5276-11eb-9792-8779966a8e4a.png)

**Comment by pzhlkj6612** [comment]
用户能够在设置中指定时间戳格式，我赞同。另外，默认用两位小数吧。

现在的软件能够正确读取两位小数的时间戳吗？

**Comment by WangShiSoftware** [comment]
> 现在的软件能够正确读取两位小数的时间戳吗？

应该是可以的
https://github.com/BesLyric-for-X/BesLyric-for-X/blob/21c5f48a429dda8e18b9c4aa030a66229a2afd69/Entities/LrcProcessor.cpp#L105-L126

我再次去看了一下之前我在[博客](https://www.cnblogs.com/BensonLaur/p/12605081.html)里，对网易云音乐官方说明的截图，官方说明里都出现了2位和3位的：
![不见图请翻墙](https://user-images.githubusercontent.com/50856253/104086444-1fac7c80-5293-11eb-810f-51e28433c5b9.png)

> 用户能够在设置中指定时间戳格式，我赞同。另外，默认用两位小数吧。
确实是会省事些，可以这么考虑。

不知道有没有可能存在另一些软件，只支持 3 位小数不支持 2 位小数，或许可以出现后再考虑

**Comment by BensonLaur** [comment]
@pzhlkj6612 
> 现在的软件能够正确读取两位小数的时间戳吗？

应该是可以的
https://github.com/BesLyric-for-X/BesLyric-for-X/blob/21c5f48a429dda8e18b9c4aa030a66229a2afd69/Entities/LrcProcessor.cpp#L105-L126

我再次去看了一下之前我在[博客](https://www.cnblogs.com/BensonLaur/p/12605081.html)里，对网易云音乐官方说明的截图，官方说明里都出现了2位和3位的：
![不见图请翻墙](https://user-images.githubusercontent.com/50856253/104086444-1fac7c80-5293-11eb-810f-51e28433c5b9.png)

> 用户能够在设置中指定时间戳格式，我赞同。另外，默认用两位小数吧。
确实是会省事些，可以这么考虑。

不知道有没有可能存在另一些软件，只支持 3 位小数不支持 2 位小数，或许可以出现后再考虑

**Comment by pzhlkj6612** [comment]
> 不知道有没有可能存在另一些软件，只支持 3 位小数不支持 2 位小数，或许可以出现后再考虑

赞同。

**Comment by pzhlkj6612** [comment]
之后用正则表达式做这个[时间标签匹配](https://github.com/BesLyric-for-X/BesLyric-for-X/blob/21c5f48a429dda8e18b9c4aa030a66229a2afd69/Entities/LrcProcessor.cpp#L105-L126)。

**Comment by BensonLaur** [comment]
Fixed by  #121
