### ISSUE TITLE
windows下构建时报错：missing -D__STDC_FORMAT_MACROS / #define __STDC_FORMAT_MACROS

### ISSUE THREAD

**Issue by obweix** [BesLyric-for-X/BesLyric-for-X#131]
windows下构建时报错：missing -D__STDC_FORMAT_MACROS / #define __STDC_FORMAT_MACROS

**Comment by pzhlkj6612** [comment]
你好。

这个问题已在 f1c6b07332c8430da2dd1ab86e3cac8d4f122b99 中修复：
- [/Entities/MusicPlayer/musicPlayer.h#L22](https://github.com/BesLyric-for-X/BesLyric-for-X/blame/f1c6b07332c8430da2dd1ab86e3cac8d4f122b99/Entities/MusicPlayer/musicPlayer.h#L22)
- [/Entities/MP3Editor/ffmpegDefine.h#L15](https://github.com/BesLyric-for-X/BesLyric-for-X/blame/f1c6b07332c8430da2dd1ab86e3cac8d4f122b99/Entities/MP3Editor/ffmpegDefine.h#L15)

你可以 pull 最新的源代码尝试构建。

<br>

感谢你花时间进行测试。

**Comment by pzhlkj6612** [comment]
@obweix 你好。你是否已经解决了这个问题呢？

**Comment by obweix** [comment]
你好，拉取代码后已经解决了，感谢~

**Comment by obweix** [comment]
> @obweix 你好。你是否已经解决了这个问题呢？

你好，拉取代码后已经解决了，感谢~
