### ISSUE TITLE
歌词预览显示效果不佳

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#152]
现有显示效果字体可能偏大，对于过长的歌词的显示也有重叠问题
![image](https://user-images.githubusercontent.com/11558955/116804486-b908e280-ab51-11eb-97e9-d566d2118ef1.png)

可参考目前最新版本网易云音乐效果进行微调
![image](https://user-images.githubusercontent.com/11558955/116804528-f8373380-ab51-11eb-98ef-a830c9a1c489.png)

**Comment by BensonLaur** [comment]
经过 #153 的修改之后，目前在这边 Win10 上效果看上去字体还是稍微偏大（`CalculateFontPointSizeWithDelta` 函数传入3）

https://github.com/BesLyric-for-X/BesLyric-for-X/blob/fb6961e01d3aa15d4ad5826df25ff01980c8034e/Entities/SkinFactory/ISkin.h#L98-L101

![`CalculateFontPointSizeWithDelta` 函数传入3](https://user-images.githubusercontent.com/11558955/116895185-805a2d80-ac65-11eb-9951-51a10997dcb0.png)


作为对比，这里分别尝试传入 2 和 1：
![`CalculateFontPointSizeWithDelta` 函数传入2](https://user-images.githubusercontent.com/11558955/116895995-581efe80-ac66-11eb-8771-4e6a4137dbbe.png)
![`CalculateFontPointSizeWithDelta` 函数传入1](https://user-images.githubusercontent.com/11558955/116896015-5d7c4900-ac66-11eb-95be-9fcd9446e9f0.png)

看上去，对于这边的显示，13pt 的字体大小偏大，11pt 的字体大小偏小，12pt 则相对比较顺眼。

所以可以在这里考虑传入 `CalculateFontPointSizeWithDelta` 函数的值为 2

**Comment by pzhlkj6612** [comment]
> 所以 经过 #153 的修改（行间隔和行高的计算上的修改）之后，这里可以考虑传入 `CalculateFontPointSizeWithDelta` 函数的值为 2

好。不过这个要单独开 PR ，因为要进行多个平台的测试。

**Comment by zhumingyu** [comment]
ubuntu 20.04 test ok!
