### ISSUE TITLE
程序中四个 `TableView` 的代码存在重复和冗余，需要精简其代码

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#161]
一开始实现的时候，由于四个 `TableView` 的实现有很多相似的逻辑，在实现具体不同的TableView类的过程中，为了提高速度，直接复制了较多代码，而在实现后没有及时删除，减低了可读性和可维护性。

#### 1. 没有使用的代码
四个 `TableView` 都有 `deleteAllItems()` 函数，而实际上被使用的，只有搜索歌词页面的 `BesLrcTableView` 的 `deleteAllItems()`有被调用

https://github.com/BesLyric-for-X/BesLyric-for-X/blob/dcb07041cc300bb7eb9f4ce90b38b7d4b978dc7e/MiddleWidgets/SubPageDownloadLyric.cpp#L408

#### 2. 其他不再使用的注释

比如：
https://github.com/BesLyric-for-X/BesLyric-for-X/blob/a4f5d38dff119bce73afc79e549c7318ecb4fe0f/BesWidgets/table/BesLListTableView.cpp#L34-L39

#### 3. 没有必要的代码
同时，在修复  #159 问题时，发现了这四个  `TableView` 中在刷新数据时，不必要地调用了 `update()` 函数。

比如：
https://github.com/BesLyric-for-X/BesLyric-for-X/blob/a4f5d38dff119bce73afc79e549c7318ecb4fe0f/BesWidgets/table/BesLListTableView.cpp#L41-L48

类似这样的逻辑，只需要保留 `emit m_model->layoutChanged();`以下代码即可，而`this->update(); `可删除

**Comment by BensonLaur** [comment]
注意到上面提到的第3点

> #### 3.没有必要的代码
> 同时，在修复 #159 问题时，发现了这四个 TableView 中在刷新数据时，不必要地调用了 update() 函数。

由于该更改和 #160 有所重合，为了避免不必要的冲突和有个相对清晰的修改记录，建议在合并 #159 PR 之后，在合并后的代码的基础上再进行修改。

**Comment by pzhlkj6612** [comment]
> 由于该更改和 #160 有所重合，为了避免不必要的冲突和有个相对清晰的修改记录，建议在合并 #159 PR 之后，在合并后的代码的基础上再进行修改。

了解。
