### ISSUE TITLE
自动往歌词单“制作历史”里添加歌曲时，默认添加到第一项位置

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#166]
### 需求说明
1. 对于“`制作历史`”歌词单来说， 最新制作的放在最前，*“默认添加到最开始”* 比 *“默认添加到最后”* 本身更合理。
2. 对于其他`自定义的歌词单`，这里认为保持 *“默认添加到最后”* 更合理，理由如下：
    + 不同于“`制作历史`”自动添加，自定义添加的数据，我觉得更应该遵循 “先来后到” 的顺序从上到下排列
    + 呼应后续要实现的封面显示功能（ #164），由于封面显示设计为显示第一项歌曲封面，同时设计上又暂时没有支持自定义封面的想法，所以如果用户想要固定封面，那么第一项就不能频繁变换，所以 保持 *“默认添加到最后”* 就比较有利于这种情况。另外由于已经实现了拖动功能（#163），添加后用户也可以随意再调整。

**Comment by pzhlkj6612** [comment]
你好。程序中似乎不存在名为“制作历史”的歌词单，而应该是“制作记录”：

https://github.com/BesLyric-for-X/BesLyric-for-X/blob/44e680f4ef8ae498b3fa7db543e83f02bdf82fc6/Entities/LyricListManager.cpp#L114

https://github.com/BesLyric-for-X/BesLyric-for-X/blob/44e680f4ef8ae498b3fa7db543e83f02bdf82fc6/Entities/LyricListManager.cpp#L131

**Comment by BensonLaur** [comment]
是的，我后面检查也注意到了，我凭记忆直接写的，把曾经的两个命名混淆了。
https://github.com/BesLyric-for-X/BesLyric-for-X/blob/44e680f4ef8ae498b3fa7db543e83f02bdf82fc6/BesWidgets/list/BesList.cpp#L263-L281

有些 commit 信息里可能也有写混了，不过由于后续才发现修改比较麻烦，commit 里的就不修改了罢，这里可以改一改

**Comment by pzhlkj6612** [comment]
好的，没问题。
