### ISSUE TITLE
将歌词单列表中将上面的项拖到下面时，顺序出错

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#168]

**Comment by pzhlkj6612** [comment]
你好。我没看懂你所描述的问题，能否请你添加重现的方法呢？如果有截图就更好了。

**Comment by BensonLaur** [comment]
这个我之前的实现是，先抽出被拖动数据项，再插入目标位置
https://github.com/BesLyric-for-X/BesLyric-for-X/blob/44e680f4ef8ae498b3fa7db543e83f02bdf82fc6/BesWidgets/list/BesList.cpp#L147-L161
之前没有考虑到，如果抽出的是后面的，插入到前面，那么逻辑没问题；问题出在如果我抽出的是前面的项，插入到靠后的目标位置时，整个队列项目以及减小了1，从抽出的项开始以后的项的小标以及小了1了，所以这种情况目标下标得减1

![图片](https://user-images.githubusercontent.com/11558955/126668981-5585af5f-d7ab-46b0-ac4e-73613a9c2f51.png)

比如上图，从4拖到1没问题，从1拖到4就有问题了

**Comment by BensonLaur** [comment]
> 你好。我没看懂你所描述的问题，能否请你添加重现的方法呢？如果有截图就更好了。

哦，还有值得注意的是，如果多个歌词单都没有任何数据，拖动测试时这个问题从界面上是看不出问题的。如果每个歌词单都有不同的数据，从前拖到后，界面上才能看出来。

之所以会这样，是因为这里左侧的歌词单列表使用了 `QListWidget`，所以实际上界面上左侧列表显示的文字，在显示以及拖动时操作的并不是真正的歌词单数据，这里的实现只是在拖动时，并行地同步地维护着实际的数据。

**Comment by pzhlkj6612** [comment]
> 比如上图，从4拖到1没问题，从1拖到4就有问题了

好的，复现了。

> 如果多个歌词单都没有任何数据，拖动测试时这个问题从界面上是看不出问题的。如果每个歌词单都有不同的数据，从前拖到后，界面上才能看出来。

明白。在使歌词单的名称互不相同后，问题被暴露了出来。

拖动前：

| index | display name | actual data
|:-:|:-:|:-:
| 0 | 0 | 0
| 1 | 1 | 1
| 2 | 2 | 2

将名称为 0 的项目（即列表中第一个项目）向下拖动到名称分别为 1 和 2 的两个项目之间：

| index | display name | actual data
|:-:|:-:|:-:
| 0 | 1 | 1
| 1 | 0 | 2
| 2 | 2 | 0

而我们期望的是：

| index | display name | actual data
|:-:|:-:|:-:
| 0 | 1 | 1
| 1 | 0 | 0
| 2 | 2 | 2

可以看到，歌词单列表中某些项目的名称与其实际的数据不符，即列表中的项目发生了错位。
