### ISSUE TITLE
需要尽快发布新版本 v3.2.0

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#180]
### 背景
随着时间推移，#108（2020年12月6日） 对应的更改 #109 中，对于 `Beslyric-for-X.pro`文件的更改，已经和已有的代码有冲突。
为了简化处理，直接废弃 #108，在此新建新的 issue

### 发布新版本前任务
1. 完成 #181
2. 完善 `README.md`. 现有 master 分支中的 `README.md`，已经完全过时. 现在新的配置过程已经在 [BesLyric-for-X_Conf](https://github.com/BesLyric-for-X/BesLyric-for-X_Conf) 项目中比较详尽地给出，开发说明直接引用过去即可 (#184)
3. 完成 #186  
4. 完成各个平台的打包工作

### 自上个版本的更新总结

- 功能
  - 歌词制作
    - #99 修复制作歌词过程中编辑歌词时的播放和暂停不合理的问题
    - #121 输出的时间标签格式由3位小数位调整为2位小数位 
  - 歌曲歌词下载
    - #98 解决获取到的歌词内容为空的问题
    - #103 #105 #106 修复文件名称含有特殊字符时保存失败问题 
  - 歌词单页面
    - #158 隐藏歌词单表格显示表左侧表头
    - #160 删除歌词单表格的数据时，恰当地刷新歌词单表格 
    - #165 支持歌词单表格的行拖动功能
    - #167 优化添加 "制作记录" 记录的方式
    - #169 修复拖动左侧歌词单列表项后乱序的问题
    - #173 修复新增加的歌词单项的图标固定为黑色背景图标的问题
    - #176 修复拖动左侧歌词单列表之后，右侧歌词单表项和左侧不对应问题
    - #178 优化拖动左侧列表项的效果
    - #179 新增自动更新和显示歌词单封面的功能
    - #197
  - 音频处理与控制
    - #100 修复某些歌曲播放结束时程序崩溃问题
    - #154 修复播放速率异常问题
  - 设置
    - #101 使用新的数据文件路径以解决权限问题 
    - #122
  - 界面
    - #120 调整了标签‘当前版本号：’的宽度 
    - #125 完善图标
    - #144 调整缩放
    - #145 调整字体
    - #147 尺寸自适应优化
    - #153 优化歌词显示
    - #182 调大若干控件大小
    - #183 优化设置页面说明，新增加 QQ 群和提交 Issue 等反馈渠道的提示
    - #202 (patch for #183)
    - #194 添加软件使用的图标的来源说明
    - #189 优化保存lrc时的错误提示，优化过长的提示
    - #196
    - #193 去除不对齐的皮肤盒子小三角形
    - #200
    - #201
  - 统计
    - #119
    - #203 
- 代码
  - 优化
    - (编译) #86 
    - (系统) #111
    - (构建 | 风格) #112
    - (构建) #113 
    - (构建) #126
    - (构建) #137
    - (构建) #142
    - (运行依赖) #123
    - (运行依赖) #133
    - (版本信息) #127 
    - (版本信息) #128 
    - (版本信息) #129 
    - (版本信息) #132
    - (版本信息) #138
    - (版本信息) #139
    - (版本控制) #134
    - (打包) #135
    - (打包) #136
    - (打包) #140
    - (打包) #141
    - (未分类) #143
    - (规范) #146 去除不必要代码
    - (规范) #151
    - (规范) #156 (#155)
    - (规范) #162 (#161)
    - (规范) #171 (#170)
    - (规范) #174 
    - (规范) #190 避免调用 unix 不支持的 strcpy_s
    - (文档) #187 更新过时的说明文档
    - (重构) #190 简化代码，避免不必要的字符串复制操作
  - 版本与升级
    - #110 (#29)
    - #124
  - 模块依赖
    - #195 引入各平台打包说明的 git 子模块   

（待更新）

**Comment by xiebruce** [comment]
支持！大佬们辛苦了！
