### ISSUE TITLE
发布新版本前，需要再微调完善下界面等

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#181]
- 关于字体变大. 
  - 整体来说，之前的字号尺寸确实偏小，特别时在 Mac 上，在 #145 之后，好看很多了
  - 存在小部分界面，在字体变大后控件尺寸相对较小，需要再微调
 
|例|1|2|
|-|-|-|
|截图|![图片](https://user-images.githubusercontent.com/11558955/126513534-3d925402-88a5-49b8-a16a-1536c80bf54c.png)|![图片](https://user-images.githubusercontent.com/11558955/126513639-2886e088-8d72-4047-8cea-ea4a33e4d6c0.png)|
- 关于构建版本的 SHA-1 hash 显示（于 57a67537952a3e414ef6fb6a9da67d9bd5612e0a 引入）
  - 好处是可以复制构建版本的 hash 值，方便定位问题
  - 缺点是对于非开发者用户，这个显示的值是没有“使用功能”上的意义的，显示会造成困惑
  - 可以考虑如何兼顾上面两点，既显示能够在需要时获取该 hash 值，同时又最大程度避免普通用户的困惑

**Comment by pzhlkj6612** [comment]
你好。

> BensonLaur:
> - 关于构建版本的 SHA-1 hash 显示
>   - 缺点是对于非开发者用户，这个显示的值是没有“使用功能”上的意义的，显示会造成困惑

我们已于 2/26/2021 11:17:18 PM 在 QQ 上针对这一点进行了交流并达成了共识。你当时的理由与现在的相同，我当时的回答是“客户会忽略他们看不懂的东西”，请你检查这个时间段的聊天记录。

不过，现在我认为你说的有道理。我将“在程序中包含哈希值”和“直接显示哈希值”的理由，以及相关的改进建议列在下面：

1. 在程序中包含哈希值是为了应对一些特殊情况，例如正式版的撤回后重发和测试版的情况收集。在这些情况下，一个版本号会对应多个不同的应用程序，因此我们需要通过一个唯一的识别码对它们进行区分，哈希值正是这样的识别码；
2. 在实现上，直接显示哈希值是非常简单的；
3. 在用户的使用上，我曾经认为“客户（用户）会忽略他们看不懂的东西”；我现在的观点是，无论用户能否理解，这个字符串都是可以被解释和说明的，这是对用户的尊重。因此，我建议在其之前添加一段说明文字，例如“ SHA-1 值：”。添加说明文字能够使用户准确找到该哈希值并在需要时提供给我们，避免他们陷入盲目寻找“版本号下方那一个英文和数字的字符串”的境地。

期待你的看法。

**Comment by BensonLaur** [comment]
> 我现在的观点是，无论用户能否理解，这个字符串都是可以被解释和说明的，这是对用户的尊重。因此，我建议在其之前添加一段说明文字，例如“ SHA-1 值：”。添加说明文字能够使用户准确找到该哈希值并在需要时提供给我们，避免他们陷入盲目寻找“版本号下方那一个英文和数字的字符串”的境地。

同意，确实给出文字说明可理解性就提高了不少。

那后续就是如何微调布局的问题了。

|设计|1|2| 
|-|-|-|
|参考图|![图片](https://user-images.githubusercontent.com/11558955/126587640-4d815a21-4f30-4e4e-a05b-c3da2bfb8ea7.png)|![图片](https://user-images.githubusercontent.com/11558955/126587657-b0dc628e-e1a4-47ac-86b6-25a7859b068f.png)|

**Comment by BensonLaur** [comment]
噢，另外这个 SHA-1 的位置我总感觉怪怪的，刚才我想我知道大概的原因了。

我曾经从某个地方（应该是B站视频，是一个日本主妇在分享其收纳心得，类似[这篇文章](https://www.517japan.com/viewnews-101360.html)）得到到一点点收纳整体的心得——一个地方是否整洁，一个关键点是这个物品是否在功能上属于这个区域，如果不是，就很有很能会让人产生杂乱感，比如在床上放了几件衣服（床上只放枕头被子，衣服则放入衣柜，这样会整洁很多）

这里感觉怪怪的，应该有类似这样的原因。“升级”这个分类下，“检测新版本” 和 "显示版本号" 是比较自然的设计，而 “版本SHA-1值” 虽然和 “版本号” 有直接关联，但是和 “升级” 这个分类关联性相对弱些，如果要说出一个分类，或许类似 “版本信息” 的分类更合适些（当然并不是说要加上这个新分类） 

不过要说怎么设计更合适一些，我倒是暂时没有更好的设计

**Comment by BensonLaur** [comment]
### 参考设计1: QTCreator

![图片](https://user-images.githubusercontent.com/11558955/126593569-1fe594a4-a902-48f4-a5df-cd7326967134.png)

在这里，软件信息在菜单中弹出，在 "关于Qt Creator"窗口中，集中显示了所有 Qt 版本，构建时间，版本控制提交哈希值

----
### 参考设计2：[qTox](https://github.com/qTox/qTox/releases/tag/v1.17.3)

![图片](https://user-images.githubusercontent.com/11558955/126593464-8c093818-0712-4c41-9ff4-4727ff0f2ae4.png)

在这里，软件在"关于" tab 页面下的 “版本” 这一组信息中，显示了相关版本号，以及 [带有链接的哈希值](https://github.com/qTox/qTox/commit/8eed684c37bd711de2ca4bd863f5f0509edcdc2d)

值得参考的一点是，qTox这里有一个不错的设计，专门提供 “已知问题”这一组信息 : [单击这里提交漏洞报告](https://github.com/qTox/qTox/issues/new?body=%23%23%23%23%23%20Brief%20Description%0A%0AOS%3A%20Windows%2010%20(10.0)%0AqTox%20version%3A%20v1.16.3%0ACommit%20hash%3A%208eed684c37bd711de2ca4bd863f5f0509edcdc2d%0Atoxcore%3A%200.2.3%0AQt%3A%205.9.6%0AHardware%3A%20%0A%E2%80%A6%0A%0AReproducible%3A%20Always%20/%20Almost%20Always%20/%20Sometimes%20/%20Rarely%20/%20Couldn%27t%20Reproduce%0A%0A%23%23%23%23%23%20Steps%20to%20reproduce%0A%0A1.%20%0A2.%20%0A3.%20%E2%80%A6%0A%0A%23%23%23%23%23%20Observed%20Behavior%0A%0A%0A%23%23%23%23%23%20Expected%20Behavior%0A%0A%0A%23%23%23%23%23%20Additional%20Info%0A(links,%20images,%20etc%20go%20here)%0A%0A----%0A%0AMore%20information%20on%20how%20to%20write%20good%20bug%20reports%20in%20the%20wiki%3A%20https%3A//github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.%0A%0APlease%20remove%20any%20unnecessary%20template%20section%20before%20submitting.)

----

我觉得可以考虑，在 BesLyric-for-X 设置页面中参考 qTox 设计，将哈希值值显示到 “关于” 下，同时提供类似的反馈问题的方法，使得用户点击链接时，直接携带版本信息，跳到 issue 页面填写问题反馈：
![图片](https://user-images.githubusercontent.com/11558955/126594852-29ddfb7a-a6e0-48b0-ac77-b4742d0e11a1.png)

**Comment by pzhlkj6612** [comment]
> 在程序中包含哈希值是为了应对一些特殊情况，例如正式版的撤回后重发和测试版的情况收集。在这些情况下，一个版本号会对应多个不同的应用程序，因此我们需要通过一个唯一的识别码对它们进行区分，哈希值正是这样的识别码；

经过考虑，我认为在任何情况下，发布的正式版都不应该使用已被使用的版本号。在修复前一个正式版的问题后，我们应更新 patch ，即版本号的第三位，再发布下一个正式版，使这个新的正式版拥有更高的版本号。这样做能使我们在收到用户反馈后直接找到对应版本的代码，也能避免用户因寻找哈希值而陷入麻烦。
