### ISSUE TITLE
皮肤盒子箭头对不齐，不好看，删掉

### ISSUE THREAD

**Issue by BensonLaur** [BesLyric-for-X/BesLyric-for-X#191]
如图，皮肤盒子箭头对不齐
![图片](https://user-images.githubusercontent.com/11558955/127518163-ac1b6451-83ac-4cde-a03c-5e437909389a.png)

**Comment by pzhlkj6612** [comment]
在一个 1920x1080 分辨率的 Windows 10 的桌面上，皮肤盒子的箭头（下）与皮肤切换按钮（上）的位置差异：

![20210730-SkinBoxWidget-indicatorPixmap-not_accurate-Windows_10-1920_1080](https://user-images.githubusercontent.com/29089388/127584883-97df632d-17eb-4169-83c0-6092d94cc566.png)
