### ISSUE TITLE
固定窗口大小太不友好了，那么大窗口拖动文件操作有点难受，望改进~

### ISSUE THREAD

**Issue by Whtie4622** [Beslyric-for-X/Beslyric-for-X#2]

**Comment by BensonLaur** [comment]
顺便做个调查，你现在使用的分辨率是多少的呢？

**Comment by BensonLaur** [comment]
你好，后来做了分辨率调整了，暂未发布，感谢之前的反馈！

**Comment by zxdawn** [comment]
![resolution](https://user-images.githubusercontent.com/30388627/47890497-04ab7a00-de8a-11e8-8fa2-ec53c8cc88e2.png)
分辨率: 3840x2160

**Comment by BensonLaur** [comment]
wow~  这就尴尬了，贫穷限制了的想象力，看来还是调整的不够，我只调整了小于 1920 x 1080 的情况，看来得再调整一下了 ：）

**Comment by zxdawn** [comment]
哈哈，不急～慢慢来

**Comment by BensonLaur** [comment]
嘻嘻，后面发布了再 @zxdawn @ 一下你，现在看来只有你能看到 3840 x 2160 的效果了

**Comment by zxdawn** [comment]
@BensonLaur 4K显示正常~多谢！
![image](https://user-images.githubusercontent.com/30388627/50319790-13b2be00-0504-11e9-9c3e-50c0cdc6343f.png)

**Comment by BensonLaur** [comment]
哈哈，这需求拖了挺久的了。我还在想百度云盘下载那么慢，用户会不会下载不了呢。由于临时发现 3.1.0 的检测更新链接失效，软件不会自动提示更新，今天稍晚些会重新替换已发布的 3.1.0 ~

**Comment by zxdawn** [comment]
@BensonLaur 推荐一下这个百度网盘的repo，下载速度很快的。

**Comment by BensonLaur** [comment]
@zxdawn 试了一下非常的快，感谢分享！

**Comment by zxdawn** [comment]
@BensonLaur 
预览页面在4K屏显示不正常：

![image](https://user-images.githubusercontent.com/30388627/52853730-6bae1f80-3157-11e9-99fc-10531a905e5d.png)

**Comment by BensonLaur** [comment]
噢哦 歌词字号显示太大了，记下了，后面更新调一调~

**Comment by pzhlkj6612** [comment]
本 issue 提到的问题已基本解决，故关闭。
UI 依然有很多问题，将会在之后开新的 issue 。
