### ISSUE TITLE
快速双击播放列表中的歌曲会卡死

### ISSUE THREAD

**Issue by yujunjiex** [Beslyric-for-X/Beslyric-for-X#23]
Beslyric版本：3.1.0.0
测试环境：QT5.6  mingw32

当我多次点击歌词单列表的歌曲时，会出现卡死现象。
客户端也存在该情况
源码debug提示`no data in list for 1e8 times access`

**Comment by BensonLaur** [comment]
好这个后面测测看

**Comment by pzhlkj6612** [comment]
有的时候打开刚播第一首歌也会这样，debug输出很多```no data in list for 1e8 times access```。

**Comment by BensonLaur** [comment]
连续在10多首歌的列表中，快速双击100多下切换播放，好像也复现不了

**Comment by yujunjiex** [comment]
@BensonLaur 
会不会是存在某个解码器的依赖，这边正常环境的两台机器存在这个问题。
如果可能的话，建议可以虚拟机测试一下。辛苦啦~

**Comment by pzhlkj6612** [comment]
@yujunjiex 如果仅关注输出很多`no data in list for 1e8 times access`的问题，是因为这里的代码：

https://github.com/BensonLaur/Beslyric-for-X/blob/0dee64a8834f1ba294b12f99fee97acc438ee500/Entities/MusicPlayer/musicPlayer.cpp#L191-L195

尝试了一亿次，却并没跳出所在的那个`while(true)`循环，所以改一下：

``` diff
             if (tryTimes >= 100000000LL) 
 { 
 	qDebug() << "no data in list for 1e8 times access"; 
 	AGStatus = AGS_FINISH; 
+  	return -1;
 } 
```

**Comment by pzhlkj6612** [comment]
在 0175326182c6d4e284cd23c657480e6bbf18b896 中移除了相关逻辑，现在在 Windows 平台上快速切歌出现卡死的情况**基本**消失，故关闭本 Issue 。
另外，要想完全杜绝此类问题，需要对播放逻辑进行重构，这个需要较长的时间来完成。
