### ISSUE TITLE
搜索功能失效

### ISSUE THREAD

**Issue by devilintheEden** [Beslyric-for-X/Beslyric-for-X#27]
![Beslyric-for-X_t0fWHyhpVl](https://user-images.githubusercontent.com/28946043/63732941-794e0b80-c844-11e9-9928-cd655430f5bb.png)

**Comment by WangShiSoftware** [comment]
![image](https://user-images.githubusercontent.com/50856253/64696320-b36c0e00-d4d0-11e9-8809-81b4ec1afa7f.png)
这边好像不会耶

**Comment by devilintheEden** [comment]
这边还是不行。版本号是3.1.1。而且点旁边的检测更新会显示无法连接网络但是网络是好的。也有可能是因为国外用户的问题吗。

**Comment by BensonLaur** [comment]
有可能

**Comment by BensonLaur** [comment]
另外这边点击 “检测更新”也会显示无法连接网络，这一点应该是bug

**Comment by pzhlkj6612** [comment]
@devilintheEden 问题已在 v3.1.2 中修复。
