### ISSUE TITLE
Segmentation fault (Linux)

### ISSUE THREAD

**Issue by zxdawn** [BesLyric-for-X/BesLyric-for-X#3]
如题，运行`./Beslyric-for-linux.sh`，得到以下报错：

```
链接目录:/home/xin/Software/Beslyric-for-linux/.:/home/xin/Software/Beslyric-for-linux/Beslyric-for-linux-deployed
Segmentation fault
```

Linux版本：Debian 9.5

**Comment by BensonLaur** [comment]
你好，感谢你对该问题的反馈，这个我开发运行的时候还只是在虚拟机里 ubuntu 18.04.1 LTS 上测试过，脱离开发环境的其他环境限于当前精力还没能做详细测试。

个人对 linux 环境下部署也是刚接触，不知阁下有没有兴趣一起推动这个 Beslyric-for-X 的linux 版本发布呢？ ：） @zxdawn

**Comment by zxdawn** [comment]
@BensonLaur 哈哈，挺感兴趣的。我没有用过Qt，所以不太了解。我建议你可以用win10的debian测试一下～

**Comment by BensonLaur** [comment]
好像是的，你接触比较多的似乎是 python 方面的编程；linux 下的测试估计确实得下载多个版本在虚拟机上跑一跑看看，可能是少了那些运行需要的库。

**Comment by BensonLaur** [comment]
cool , 物理方面的，很赞！

有心了，不过很遗憾其实我也还没有具体的思路 ，可能我这个周末或者下个周末再自己具体看一下吧，更新新的用户建议的功能之后，再具体去测试测试~

**Comment by ShuiHuo** [comment]
哇，原来这问题已经两年了呀……

**Comment by pzhlkj6612** [comment]
@ShuiHuo 你好。

不好意思，现在 BesLyric-for-X 还没有可用的 Linux 版本。

我们的计划是发布 AppImage 包，同时也会编写相关的开发文档供用户从源码构建这个软件。

请再等一等。

**Comment by zhumingyu** [comment]
> @ShuiHuo 你好。
> 
> 不好意思，现在 BesLyric-for-X 还没有可用的 Linux 版本。
> 
> 我们的计划是发布 AppImage 包，同时也会编写相关的开发文档供用户从源码构建这个软件。
> 
> 请再等一等。

Hi,有没有详细的自编译faq,thx!

**Comment by pzhlkj6612** [comment]
@zhumingyu

**Comment by zhumingyu** [comment]
> @zhumingyu

你好，？

**Comment by pzhlkj6612** [comment]
@zhumingyu 

你好。请参阅 https://github.com/BesLyric-for-X/BesLyric-for-X_Conf

这个文档现在还不稳定，经常会有通过 force-push 进行的更新，但我会保证你在线上看到的版本是始终可用的。你可以加 QQ 群 1021317114 来参与讨论，谢谢。

不好意思，刚才点错了，没写完就发出去了。

**Comment by zhumingyu** [comment]
@pzhlkj6612 
thx very much！
