### ISSUE TITLE
考虑收集用户的操作系统信息

### ISSUE THREAD

**Issue by pzhlkj6612** [BesLyric-for-X/BesLyric-for-X#63]
好处：
- 有更多信息用来分析用户群体。

坏处：
- 暴露更多的用户信息。

关联：
- https://github.com/Beslyric-for-X/Beslyric-for-X/issues/29#issuecomment-589970648

**Comment by BensonLaur** [comment]
这个原则上还是经量少收集用户的信息，之前 [收集登陆 IP](https://www.cnblogs.com/BensonLaur/p/6262565.html#title_4_4) 倒是给了我后来更新的一些动力，让我不至于不清楚是否真的有人在用。

这个是否决定 [收集用户的操作系统信息] ，我觉得可以从是否有助于将来改善软件这一点来考虑，如果帮助不大我个人觉得可能就没必要咯
