### ISSUE TITLE
首句歌词时间戳异常

### ISSUE THREAD

**Issue by ish-kafel** [Beslyric-for-X/Beslyric-for-X#65]
刚做了一首歌，音乐一开始就是第一句歌词，在默认提前300ms的情况下，最终生成第一句的时间戳为[-909387743:51.524]，导致需要手动修改。希望可以给首句时间加个判断，小于0就插入[00:00.000]

**Comment by ish-kafel** [comment]
我使用的windows的3.1.1版本

**Comment by BensonLaur** [comment]
感谢反馈，应该是你提到的情况没有处理

**Comment by BensonLaur** [comment]
进一步发现是应该 记录时间的变量 curAudioPos 还没来得及被初始化就推上标记了一行导致

https://github.com/Beslyric-for-X/Beslyric-for-X/blob/master/MiddleWidgets/SubPageMaking.cpp#L489-L495

**Comment by ish-kafel** [comment]
应该是，我点完开始制作马上就按了上键推上

**Comment by pzhlkj6612** [comment]
8b5141f5ba94899ea2e6ae3fb235f0459abcf671 的修复似乎没找到关键点，等会我做个提交。

**Comment by BensonLaur** [comment]
> [8b5141f](https://github.com/Beslyric-for-X/Beslyric-for-X/commit/8b5141f5ba94899ea2e6ae3fb235f0459abcf671) 的修复似乎没找到关键点，等会我做个提交。

哦噢，好像是的，这个还被封装起来了

https://github.com/Beslyric-for-X/Beslyric-for-X/blob/8b5141f5ba94899ea2e6ae3fb235f0459abcf671/Entities/LyricMaker.cpp#L243-L252

**Comment by pzhlkj6612** [comment]
对，就是减去`insertOffsetTime`把时间弄错了。
